force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>This object stores logs for a salesforce transaction</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Aggregate_Queries__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Queries__c</fullName>
    <description>Returns the number of aggregate queries that have been processed with any SOQL query statement.</description>
    <inlineHelpText>Returns the number of aggregate queries that have been processed with any SOQL query statement.</inlineHelpText>
    <label>Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>the class name of the current processes</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time__c</fullName>
    <description>Returns the CPU time (in milliseconds) that has been used in the current transaction.</description>
    <inlineHelpText>Returns the CPU time (in milliseconds) that has been used in the current transaction.</inlineHelpText>
    <label>CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows__c</fullName>
    <description>Returns the number of records that have been processed with any statement that counts against DML limits, such as DML statements, the Database.emptyRecycleBin method, and other methods.</description>
    <inlineHelpText>Returns the number of records that have been processed with any statement that counts against DML limits, such as DML statements, the Database.emptyRecycleBin method, and other methods.</inlineHelpText>
    <label>DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <description>Returns the number of DML statements (such as insert, update or the database.EmptyRecycleBin method) that have been called.</description>
    <inlineHelpText>Returns the number of DML statements (such as insert, update or the database.EmptyRecycleBin method) that have been called.</inlineHelpText>
    <label>DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Email_Invocations__c.field-meta.xml
<CustomField>
    <fullName>Email_Invocations__c</fullName>
    <description>Returns the number of email invocations (such as sendEmail) that have been called.</description>
    <inlineHelpText>Returns the number of email invocations (such as sendEmail) that have been called.</inlineHelpText>
    <label>Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Retrieves the URL for the endpoint of the external server for this request.</description>
    <inlineHelpText>Retrieves the URL for the endpoint of the external server for this request.</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Heap_Size__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size__c</fullName>
    <description>Returns the approximate amount of memory (in bytes) that has been used for the heap.</description>
    <inlineHelpText>Returns the approximate amount of memory (in bytes) that has been used for the heap.</inlineHelpText>
    <label>Heap Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Returns the line number from where the exception was thrown.</description>
    <inlineHelpText>Returns the line number from where the exception was thrown.</inlineHelpText>
    <label>Line Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Returns the error message that displays for the user.</description>
    <inlineHelpText>Returns the error message that displays for the user.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Returns the type of method used by HttpRequest.</description>
    <inlineHelpText>Returns the type of method used by HttpRequest.</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>the method called</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Queries__c.field-meta.xml
<CustomField>
    <fullName>Queries__c</fullName>
    <description>Returns the number of SOQL queries that have been issued.</description>
    <inlineHelpText>Returns the number of SOQL queries that have been issued.</inlineHelpText>
    <label>Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>representing how Apex is running. e.g. BULK_API vs LIGHTNING</description>
    <inlineHelpText>representing how Apex is running. e.g. BULK_API vs LIGHTNING</inlineHelpText>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Retrieves the body of this request.</description>
    <inlineHelpText>Retrieves the body of this request.</inlineHelpText>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Retrieves the body returned in the response.</description>
    <inlineHelpText>Retrieves the body returned in the response.</inlineHelpText>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who ran process</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Returns the stack trace as a string.</description>
    <inlineHelpText>Returns the stack trace as a string.</inlineHelpText>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Retrieves the status message returned for the response.</description>
    <inlineHelpText>Retrieves the status message returned for the response.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Retrieves the value of the status code returned in the response.</description>
    <inlineHelpText>Retrieves the value of the status code returned in the response.</inlineHelpText>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>identifier for this request. Same as requestId in splunk or REQUEST_ID in event monitoring.</description>
    <externalId>true</externalId>
    <inlineHelpText>identifier for this request. Same as requestId in splunk or REQUEST_ID in event monitoring.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>API INBOUND</fullName>
            </value>
            <value>
                <fullName>EXCEPTION</fullName>
            </value>
            <value>
                <fullName>API OUTBOUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <description>Returns the type of exception, such as DmlException, ListException, MathException, and so on.</description>
    <inlineHelpText>Returns the type of exception, such as DmlException, ListException, MathException, and so on.</inlineHelpText>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Enable_Logs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Logs__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag to turn logging off or on</description>
    <inlineHelpText>Flag to turn logging off or on</inlineHelpText>
    <label>Enable Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event to submit logs</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>the line number of the exception</description>
    <label>Line Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The exception message</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Queries__c.field-meta.xml
<CustomField>
    <fullName>Queries__c</fullName>
    <label>Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description>representing how Apex is running. e.g. BULK_API vs LIGHTNING</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The exception stack trace</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>identifier for this request. Same as requestId in splunk or REQUEST_ID in event monitoring.</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <description>The exception type name</description>
    <label>Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Log.cls
/**
 * @description       : Log entry class used to create logs to monitor activity in Salesforce
 * @test class        : LogTest
 * @test coverage     : 100%
 * @author            : lukevang@lvsolutions.co
 * @group             : 
 * @last modified on  : 02-10-2021
 * @last modified by  : lukevang@lvsolutions.coteq
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   02-10-2021   lukevang@lvsolutions.co   Initial Version
 * 1.1   02-10-2021   lukevang@lvsolutions.co   Updating to include methods that allow manual enttry of classname and method
**/
global with sharing class Log {
    
    static List<Log__c> logsToInsert;
   // static List<LogEvent__e> platformEventLogs;

    /**
    * @description used to log general debug statements
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param message 
    **/
    global static void createDebugLog(String message){
        Log__c log = new Log__c ();
        log.Message__c = message;
        log.Type__c = 'DEBUG';
        addLog(log);
    }

       /**
    * @description used to log general debug statements
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param message 
    * @param className
    * @param methodName
    **/
    global static void createDebugLog(String message, String className, String methodName){
        Log__c log = new Log__c ();
        log.Message__c = message;
        log.Type__c = 'DEBUG';
        log.Class_Name__c = className;
        log.Method_Name__c = methodName;
        addLog(log);
    }
    
    /**
    * @description used to log exceptions
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param ex 
    **/
    global static void createExceptionLog(Exception ex)
    {
        Log__c log = new Log__c ();
        log.Message__c = ex.getMessage();
        log.Stack_Trace__c = ex.getStackTraceString();
        log.Type__c = 'EXCEPTION';
        log.Line_Number__c = ex.getLineNumber();
        log.Type_Name__c = ex.getTypeName();
        addLog(log);
    }

   /**
    * @description used to log exceptions
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param ex 
    * @param className
    * @param methodName
    **/
    global static void createExceptionLog(Exception ex, String className, String methodName)
    {
        Log__c log = new Log__c ();
        log.Message__c = ex.getMessage();
        log.Stack_Trace__c = ex.getStackTraceString();
        log.Type__c = 'EXCEPTION';
        log.Line_Number__c = ex.getLineNumber();
        log.Type_Name__c = ex.getTypeName();
        log.Class_Name__c = className;
        log.Method_Name__c = methodName;
        addLog(log);
    }

    /**
    * @description used to log outbound API calls
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param request 
    * @param response 
    **/
    global static void createOutboundAPILog(HttpRequest request, HttpResponse response)
    {
        Log__c log = new Log__c ();
        log.Request_Body__c = request.getBody() != null ? request.getBody() : null;
        log.Method__c = request.getMethod() != null ? request.getMethod() : null;
        log.Endpoint__c =request.getEndpoint() != null ? request.getEndpoint() : null;
        log.Response_Body__c = response.getBody() != null ? response.getBody() : null;
        log.Status__c = response.getStatus() != null ? response.getStatus() : null;
        log.Status_Code__c = response.getStatusCode() != null ? response.getStatusCode() : null;
        log.Type__c = 'API OUTBOUND';
        addLog(log);
    }

   /**
    * @description used to log outbound API calls
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param request 
    * @param response 
    * @param className
    * @param methodName
    **/
    global static void createOutboundAPILog(HttpRequest request, HttpResponse response,  String className, String methodName)
    {
        Log__c log = new Log__c ();
        log.Request_Body__c = request.getBody() != null ? request.getBody() : null;
        log.Method__c = request.getMethod() != null ? request.getMethod() : null;
        log.Endpoint__c =request.getEndpoint() != null ? request.getEndpoint() : null;
        log.Response_Body__c = response.getBody() != null ? response.getBody() : null;
        log.Status__c = response.getStatus() != null ? response.getStatus() : null;
        log.Status_Code__c = response.getStatusCode() != null ? response.getStatusCode() : null;
        log.Type__c = 'API OUTBOUND';
        log.Class_Name__c = className;
        log.Method_Name__c = methodName;
        addLog(log);
    }

    /**
    * @description used to log inbound api requets
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param request 
    **/
    global static void createInboundAPILog(RestRequest request)
    {
        Log__c log = new Log__c ();
        log.Request_Body__c = request.requestBody != null ? request.requestBody.toString() : null;
        log.Method__c = request.httpMethod != null ? request.httpMethod : null;
        log.Endpoint__c = request.resourcePath != null ? request.resourcePath : null;
        log.Type__c = 'API INBOUND';
        addLog(log);
    }

   /**
    * @description used to log inbound api requets
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param request 
    * @param className
    * @param methodName
    **/
    global static void createInboundAPILog(RestRequest request,   String className, String methodName)
    {
        Log__c log = new Log__c ();
        log.Request_Body__c = request.requestBody != null ? request.requestBody.toString() : null;
        log.Method__c = request.httpMethod != null ? request.httpMethod : null;
        log.Endpoint__c = request.resourcePath != null ? request.resourcePath : null;
        log.Type__c = 'API INBOUND';
        log.Class_Name__c = className;
        log.Method_Name__c = methodName;
        addLog(log);
    }
    

    /**
    * @description used to create log through platform event, only used in cases where you want to log and exception but also throw an exception
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param ex 
    **/
    // private static void createExceptionLogPE(Exception ex)
    // {
    //     LogEvent__e log = new LogEvent__e ();
    //     log.Message__c = ex.getMessage();
    //     log.Stack_Trace__c = ex.getStackTraceString();
    //     log.Type__c = 'EXCEPTION';
    //     log.Line_Number__c = ex.getLineNumber();
    //     log.Type_Name__c = ex.getTypeName();
    //     addPlatformEventLog(log);
    // }

    /**
    * @description creates platform event log
    * @author lukevang@lvsolutions.co | 02-10-2021 
    * @param log 
    **/
    // static void addPlatformEventLog(LogEvent__e log)
    // {
    //     Request reqInfo = Request.getCurrent();
    //     if(platformEventLogs == null)
    //     {
    //         platformEventLogs = new List<LogEvent__e>();
    //     }
    //     log.Transaction_Id__c = reqInfo.getRequestId();
    //     log.Quiddity__c = String.valueOf(reqInfo.getQuiddity());
    //     log.CPU_Time__c = Limits.getCpuTime();
    //     log.Aggregate_Queries__c = Limits.getAggregateQueries();
    //     log.DML_Rows__c = Limits.getDmlRows();
    //     log.DML_Statements__c = Limits.getDmlStatements();
    //     log.Email_Invocations__c = Limits.getEmailInvocations();
    //     log.Heap_Size__c = Limits.getHeapSize();
    //     log.Queries__c = Limits.getQueries();
    //     log.Running_User__c = UserInfo.getUserId();
    //     populateClassAndMethod(log);
    //     platformEventLogs.add(log);
    // }

    
    static void addLog(Log__c log)
    {
        Request reqInfo = Request.getCurrent();
        if(logsToInsert == null)
        {
            logsToInsert = new List<Log__c>();
        }
        log.Transaction_Id__c = reqInfo.getRequestId();
        log.Quiddity__c = String.valueOf(reqInfo.getQuiddity());
        log.CPU_Time__c = Limits.getCpuTime();
        log.Aggregate_Queries__c = Limits.getAggregateQueries();
        log.DML_Rows__c = Limits.getDmlRows();
        log.DML_Statements__c = Limits.getDmlStatements();
        log.Email_Invocations__c = Limits.getEmailInvocations();
        log.Heap_Size__c = Limits.getHeapSize();
        log.Queries__c = Limits.getQueries();
        log.Running_User__c = UserInfo.getUserId();
        if(log.Class_Name__c == null && log.Method_Name__c == null)
        {
            populateClassAndMethod(log);
        }
        logsToInsert.add(log);
    }

    /**
    * @description gets the executing high method and class name
    * @authorluke.vang@lvsolutions.co | 02-10-2021 
    * @param stackTrace 
    * @param log 
    **/
    private static void populateLocation(String stackTrace, Log__c log)
    {
        String stack = stackTrace.substringAfter('\n').substringAfter('\n').substringAfter('\n').substringBefore('\n');
        log.Method_Name__c = stack.substringBefore(':').subStringAfterLast('.');
        log.Class_Name__c = stack.substringBetween('Class.', '.' + log.Method_Name__c);
    }

       /**
    * @description gets the executing high method and class name
    * @authorluke.vang@lvsolutions.co | 02-10-2021 
    * @param stackTrace 
    * @param log 
    **/
    // private static void populateLocation(String stackTrace, LogEvent__e log)
    // {
    //     String stack = stackTrace.substringAfter('\n').substringAfter('\n').substringAfter('\n').substringBefore('\n');
    //     log.Method_Name__c = stack.substringBefore(':').subStringAfterLast('.');
    //     log.Class_Name__c = stack.substringBetween('Class.', '.' + log.Method_Name__c);
    // }

    /**
    * @description populates the apex class and method for each log
    * @authorluke.vang@lvsolutions.co | 02-10-2021 
    * @param log 
    **/
    static void populateClassAndMethod(Log__c log)
    {
        try{
            throw new DMLException('ex');
        }catch(Exception ex){
            populateLocation(ex.getStackTraceString(), log);
        }
    }

        /**
    * @description populates the apex class and method for each log
    * @authorluke.vang@lvsolutions.co | 02-10-2021 
    * @param log 
    **/
    // static void populateClassAndMethod(LogEvent__e log)
    // {
    //     try{
    //         throw new DMLException('ex');
    //     }catch(Exception ex){
    //         populateLocation(ex.getStackTraceString(), log);
    //     }
    // }

       /**
    * @description general function to create logs
    * @author lukevang@lvsolutions.co | 02-09-2021 
    **/
    global static void insertLogs()
    {
        if(logsToInsert != null && !logsToInsert.isEmpty() && enabled())
        {
            insert logsToInsert;
            logsToInsert.clear();
        }
    }

      /**
    * @description general function to create logs in future method
    * @author lukevang@lvsolutions.co | 02-09-2021 
    **/
    global static void insertLogsFuture()
    {
        if(logsToInsert != null && !logsToInsert.isEmpty() && enabled())
        {
            callFuture(JSON.serialize(logsToInsert));
            logsToInsert.clear();
        }
    }

    /**
    * @description 
    * @authorluke.vang@lvsolutions.co | 02-09-2021 
    * @param logs 
    **/
    @future
    global static void callFuture(String logs)
    {
        logsToInsert = (List<Log__c>) JSON.deserialize(logs, List<Log__c>.class);
        insert logsToInsert;
    }

    /**
    * @description general function to platform event logs
    * @author lukevang@lvsolutions.co | 02-09-2021 
    **/
    // private static void insertLogsPE()
    // {
    //     if(!platformEventLogs.isEmpty() && enabled())
    //     {
    //         List<Database.SaveResult> results = EventBus.publish(platformEventLogs);
    //         // Inspect publishing result for each event
    //         for (Database.SaveResult sr : results) {
    //             if (!sr.isSuccess()){
    //                 for(Database.Error err : sr.getErrors()) {
    //                     System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
    //                 }
    //             }       
    //         }
    //     }
    // }

    static Boolean enabled()
    {
        return Log_Setting__c.getOrgDefaults() == null ? false : Log_Setting__c.getOrgDefaults().Enable_Logs__c;
    }

}